name: Firsts Tests

on:
  push:
    branches:
      - main 

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: —Åheck code
      uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest 

    - name: tests
      run: |
        python3 -m unittest test.py  

  test-windows:
    runs-on: windows-latest

    steps:
    - name: check code
      uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: tests
      run: |
        python -m unittest test.py
